# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER hejiale

# 挂载目录
VOLUME /usr/local/YiZhanShi
# 创建目录
RUN mkdir -p /usr/local/YiZhanShi
# 指定路径
WORKDIR /usr/local/YiZhanShi
# 复制jar文件到路径
COPY ./jar/bishe-modules-system.jar /usr/local/YiZhanShi/bishe-modules-system.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","bishe-modules-system.jar"]